export default {
  "index": "Home",
  "-- Product": {"type":"separator","title":"プロダクト"},
  "product-vision": "プロダクトビジョン・設計原則",
  "first-release": "初回Release",
  "ubiquitous": "ユビキタス言語",
  "media": "Media",
  "community": "Community",
  "user": "User",
  "-- UI": {"type":"separator","title":"画面・UI設計"},
  "screens": "画面仕様",
  "design-system": "Design System",
  "-- System Design": {"type":"separator","title":"システム設計"},
  "system": "システム設計",
  "technology-stack": "技術スタック",
  "-- Development": {"type":"separator","title":"開発・運用"},
  "development-process": "アジャイル開発",
  "local-development": "ローカル開発",
  "test-design": "テスト設計",
  "ci-cd": "CI/CD",
  "build-deploy": "ビルド・デプロイ",
  "branch-strategy": "ブランチ運用",
  "commit-message": "コミットメッセージ",
  "versioning": "バージョニング",
  "ai-development": "AI支援開発",
  "-- Documentation": {"type":"separator","title":"ドキュメント"},
  "documentation-policy": "ドキュメント管理",
  "design-document-templates": "設計書テンプレート",
  "context": "Context"
}
