export default {
  "index": "画面仕様",
  "-- User": {"type":"separator","title":"User"},
  "user-registration": "User登録",
  "user-settings": "User設定",
  "user-settings-profile": "設定：プロフィール",
  "-- Account Deletion": {"type":"separator","title":"アカウント削除"},
  "account-deletion-flow": "フロー概要",
  "account-deletion-impact": "1. 影響確認",
  "account-deletion-community-resolution": "2. Community管理状態の解消",
  "account-deletion-community-review": "3. Community確認",
  "account-deletion-final-review": "4. 最終レビュー",
  "account-deletion-final-confirmation": "5. 最終確認",
  "-- Community": {"type":"separator","title":"Community"},
  "community-creation": "Community作成",
  "community-invitation-acceptance": "Community招待の受諾",
  "community-members": "Community参加者",
  "community-management": "Community管理",
  "community-deletion-confirmation": "Community削除確認",
  "-- Media": {"type":"separator","title":"Media・Group"},
  "personal-media": "Personal Media",
  "community-media": "Community Media",
  "media-browser-detail": "Media一覧・詳細",
  "media-upload": "Media Upload",
  "media-update": "Media Update",
  "media-sharing": "Media共有",
  "group-browser": "Group一覧・詳細"
}
