export default {
  "index": "画面仕様",
  "user-registration": "User登録",
  "user-profile": "Userプロフィール",
  "account-deletion-flow": "アカウント削除フロー",
  "account-deletion-impact": "アカウント削除：影響確認",
  "account-deletion-community-resolution": "アカウント削除：Community管理状態の解消",
  "account-deletion-community-review": "アカウント削除：Community確認",
  "account-deletion-final-review": "アカウント削除：最終レビュー",
  "account-deletion-final-confirmation": "アカウント削除：最終確認",
  "community-creation": "Community作成",
  "community-invitation-acceptance": "Community招待の受諾",
  "personal-media": "Personal Media",
  "community-media": "Community Media",
  "media-browser-detail": "Media一覧・詳細",
  "media-sharing": "Media共有",
  "media-upload": "Media Upload",
  "group-browser": "Group一覧・詳細",
  "community-members": "Community参加者",
  "community-management": "Community管理",
  "community-deletion-confirmation": "Community削除確認"
}
